# Generated by Django 3.0.6 on 2020-05-19 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('details', models.CharField(max_length=350)),
                ('image', models.ImageField(blank=True, null=True, upload_to='project_images')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
